---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pxeboot-config
  namespace: default
data:
  config.yaml: |
    dhcp_interface: net1
    bind_ip: 172.16.100.2
    dhcp_range: 172.16.100.10 - 172.16.100.100
    dns: 10.192.2.10
    password: VMware1!
    management_interface: eth0
    http_port: 8080
    nics:
      00-50-56-82-70-2a:
        ip: 10.65.101.10
        hostname: vc-01.example.org
        gateway: 10.65.146.100
        netmask: 255.255.255.0
    boot_file: efi/boot/bootx64.efi
    lease_time: 500
    root_path: /home/ubuntu/images
    ntp_server: time.svc.pivotal.io
    boot_config_file: efi/boot/boot.cfg
    kickstart_template: |
      #
      # Sample scripted installation file
      # Accept the VMware End User License Agreement
      vmaccepteula
      clearpart --overwritevmfs --alldrives
      # Set the root password for the DCUI and Tech Support Mode
      rootpw VMware1!
      # Install on the first local disk available on machine
      install --firstdisk="DELLBOSS VD",Hypervisor_0,HV,usb,IDSDM --overwritevmfs --novmfsondisk
      #install --firstdisk --overwritevmfs
      # Set the network to DHCP on the first network adapter
      network --bootproto=static --addvmportgroup=1 --ip={{.IP}} --netmask={{.NetMask}} --gateway={{.Gateway}} --nameserver={{.NameServer}} --hostname={{.HostName}}
      reboot
      %firstboot --interpreter=busybox
      vim-cmd hostsvc/enable_ssh
      vim-cmd hostsvc/start_ssh
      vim-cmd hostsvc/enable_esx_shell
      vim-cmd hostsvc/start_esx_shell
      cat > /etc/ntp.conf << __NTP_CONFIG__
      restrict default kod nomodify notrap noquerynopeer
      restrict 127.0.0.1
      server {{.NTPServer}}
      __NTP_CONFIG__
      /sbin/chkconfig ntpd on
      reboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxeboot
  labels:
    app: pxeboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pxeboot
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: vlan-dhcp-conf
      labels:
        app: pxeboot
    spec:
      containers:
        - name: pxeboot
          image: datianshi/pxeboot
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /data
      volumes:
        - name: config-volume
          configMap:
            name: pxeboot-config
---
apiVersion: v1
kind: Service
metadata:
  name: pxeboot-service
spec:
  type: NodePort
  selector:
    app: pxeboot
  ports:
    - port: 8080
      targetPort: 8080