apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-conf
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "vlan",
      "master": "eth0",
      "vlanId": 2211,
      "ipam": {
        "type": "host-local",
        "subnet": "10.65.146.0/24",
        "rangeStart": "10.65.146.200",
        "rangeEnd": "10.65.146.220",
        "routes": [
          { "dst": "0.0.0.0/0",
            "gw": "10.65.146.1"
          }
        ],
        "gateway": "10.65.146.1"
      }
    }'
